<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'LosI18n\Controller\ConsoleController'   => __DIR__ . '/src/LosI18n/Controller/ConsoleController.php',
    'LosI18n\Controller\IndexController'     => __DIR__ . '/src/LosI18n/Controller/IndexController.php',
    'LosI18n\Formatter\AbstractFormatter'    => __DIR__ . '/src/LosI18n/Formatter/AbstractFormatter.php',
    'LosI18n\Formatter\CsvFormatter'         => __DIR__ . '/src/LosI18n/Formatter/CsvFormatter.php',
    'LosI18n\Formatter\FormatterInterface'   => __DIR__ . '/src/LosI18n/Formatter/FormatterInterface.php',
    'LosI18n\Formatter\JsonFormatter'        => __DIR__ . '/src/LosI18n/Formatter/JsonFormatter.php',
    'LosI18n\Formatter\PhpFormatter'         => __DIR__ . '/src/LosI18n/Formatter/PhpFormatter.php',
    'LosI18n\Module'                         => __DIR__ . '/src/LosI18n/Module.php',
    'LosI18n\Service\BuilderService'         => __DIR__ . '/src/LosI18n/Service/BuilderService.php',
    'LosI18n\Service\BuilderServiceFactory'  => __DIR__ . '/src/LosI18n/Service/BuilderServiceFactory.php',
    'LosI18n\Service\LanguageService'        => __DIR__ . '/src/LosI18n/Service/LanguageService.php',
    'LosI18n\Service\LanguageServiceFactory' => __DIR__ . '/src/LosI18n/Service/LanguageServiceFactory.php',
];
