<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LosI18n\Module'                        => __DIR__ . '/Module.php',
    'LosI18n\Controller\IndexController' => __DIR__ . '/src/LosI18n/Controller/IndexController.php',
    'LosI18nTest\Framework\TestCase'        => __DIR__ . '/tests/LosI18n/Framework/TestCase.php',
    'LosI18nTest\SampleTest'                => __DIR__ . '/tests/LosI18n/SampleTest.php',
);
